### ISSUE TITLE
Getting: TypeError: 'undefined' is not a function (evaluating 'jasmine.addMatchers')

### ISSUE THREAD

**Issue by tedyoung** [just-boris/jasmine-collection-matchers#1]
Not sure if you can help me figure this out, but I'm trying to use this in the context of tests run via Karma (using Karma 0.12.31, Karma-Jasmine 0.3.5, and Jasmine 2.2.0). I have the jasmine-collection-matchers specified in the karma.conf.js in the files property, right before my scripts are loaded, but I get this error when running the tests:

TypeError: 'undefined' is not a function (evaluating 'jasmine.addMatchers')

Which I can't figure out how to fix. It's like it's trying to call `addMatchers()` before `jasmine` is defined, but I'm not sure where else to specify the loading of the jasmine-collection-matchers so they're usable by my tests.

**Comment by just-boris** [comment]
Hello. I am using this matchers with Karma too.
You can see an example of usage in my another repo: https://github.com/just-boris/require-mini/commit/be8f7a9a7cda2e4f21f84e4324fb54143e36468e

**Comment by tedyoung** [comment]
Thanks for the reply. It turned out that my IDE (IntelliJ IDEA) was using the wrong npm/node_modules directory, and so was using Jasmine 1.3 instead of the 2.2.0 I thought I was using.
