### ISSUE TITLE
Readme browser instructions are out of date

### ISSUE THREAD

**Issue by deckar01** [just-boris/jasmine-collection-matchers#11]
The readme section for browser usage suggests including a pack file that no longer exists from the npm package.

> **Browser**
> 
> Include combined matchers file:
> 
> ``` html
> <script src="/node_modules/jasmine-collection-matchers/lib/pack.js"></script>
> ```

The correct way seems to be to install the package with bower and include:

``` html
<script src="/bower_components/jasmine-collection-matchers/index.js"></script>
```

**Comment by just-boris** [comment]
You are right. 
Forgot to update docs after changes in #5.

Now it should be fine, thank you!

**Comment by deckar01** [comment]
Thanks for looking at this. One more improvement that might help new developers is explicitly listing the install command for bower to avoid confusion with the npm instructions.

> Install via `bower`:
> `bower install jasmine-collection-matchers`
