### ISSUE TITLE
npm version doesn't match version in repository

### ISSUE THREAD

**Issue by erykpiast** [just-boris/jasmine-collection-matchers#4]
The latest version in NPM is `0.0.10`, in repository we have `0.1.0`.

**Comment by just-boris** [comment]
published. Thanks for notice!

**Comment by erykpiast** [comment]
:)

2015-08-18 14:48 GMT+02:00 Boris Serdiuk notifications@github.com:

**Comment by jameswilddev** [comment]
Apologies but at https://www.npmjs.com/package/jasmine-collection-matchers I'm still seeing 0.0.10.  Am I looking in the right place?

Thanks.

**Comment by jameswilddev** [comment]
Apologies but at https://www.npmjs.com/package/jasmine-collection-matchers I'm still seeing 0.0.10.  Am I looking in the right place?

Thanks.

**Comment by erykpiast** [comment]
Hm, that's true.

**Comment by just-boris** [comment]
published again.
Now that page shows new version.

**Comment by jameswilddev** [comment]
Cheers, was just able to get the latest version via NPM directly and can no longer reproduce my earlier issue!  Thanks!
